# Generated by Django 4.1.2 on 2022-12-28 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyItem',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('checked', models.BooleanField(default=False)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
