# Generated by Django 4.1.2 on 2022-12-29 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_myitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyItem',
        ),
    ]
